@Library("jenlib") _

try {
	node {
		cleanWs()
	}

	inSingularity(app: "visionary-dls") {
		stage('Checkout') {
			runOnSlave(label: "frontend") {
				withWaf() {
					try {
						sish "waf setup " +
						     "--project binutils-gdb@binutils-2_25-branch-nux " +
						     "--clone-depth 1 " +
						     "--gerrit-changes=${GERRIT_CHANGE_NUMBER} " +
						     "--gerrit-url=ssh://hudson@$GERRIT_HOST:$GERRIT_PORT"
					} catch (MissingPropertyException ignored) {     // Jenkinsfile not called via Gerrit
						sish "waf setup " +
						     "--project binutils-gdb@binutils-2_25-branch-nux " +
						     "--clone-depth 1"
					}
				}
			}
		}

		stage("Build") {
			onSlurmResource(partition: "jenkins", "cpus-per-task": "8") {
				sish "bash binutils-gdb/ci/00_build_install.sh"
			}
		}
	}

} catch (Exception e) {
	notifyFailure(mattermostChannel: "#dls-software")
	throw e as java.lang.Throwable
} finally {
	// Always clean the workspace
	node {
		cleanWs()
	}
}

// Some Jenkins steps fail a build without raising (e.g. archiveArtifacts)
if (currentBuild.currentResult != "SUCCESS") {
	notifyFailure(mattermostChannel: "#dls-software")
}