#!/usr/bin/env groovy
@Library("jenlib") _

node {

	// Default to false to ensure failure messages are sent
	GERRIT_BUILD = false

	try {
		cleanWs()

		stage('Checkout') {
			withWaf() {
				try {
					sh "waf setup " +
					   "--project binutils-gdb@binutils-2_25-branch-nux " +
					   "--clone-depth 1 " +
					   "--gerrit-changes=${GERRIT_CHANGE_NUMBER} " +
					   "--gerrit-url=ssh://hudson@$GERRIT_HOST:$GERRIT_PORT"
					GERRIT_BUILD = true
				} catch (MissingPropertyException ignored) {     // Jenkinsfile not called via Gerrit
					sh "waf setup " +
					   "--project binutils-gdb@binutils-2_25-branch-nux " +
					   "--clone-depth 1"
				}
			}
		}

		stage("Build") {
			srun_with_container("bash binutils-gdb/ci/00_build_install.sh")
		}

	} catch (Exception e) {
		post_error_build_action()
		throw e as java.lang.Throwable
	} finally {
		post_all_build_action()
	}

	// Some Jenkins steps fail a build without raising (e.g. archiveArtifacts)
	if (currentBuild.currentResult != "SUCCESS") {
		post_error_build_action()
	}
}

/*
/* HELPER FUNCTIONS
*/

void srun_with_container(String command) {
	sh "srun -p jenkins -c8 --mem=29G -- singularity exec --app visionary-defaults " +
	   "/containers/jenkins/softies_darling ${command}"
}

void post_all_build_action() {
	// Always clean the workspace
	cleanWs()
}

void post_error_build_action() {
	if (!GERRIT_BUILD) {
		mattermostSend(channel: "#dls-software",
		               text: "@channel Jenkins build `${env.JOB_NAME}` has failed!",
		               message: "${env.BUILD_URL}",
		               endpoint: "https://brainscales-r.kip.uni-heidelberg.de:6443/hooks/qrn4j3tx8jfe3dio6esut65tpr")
	}
}
