@Library("jenlib") _

try {
	node {
		cleanWs()
	}

	inSingularity(app: "visionary-dls") {
		wafSetup(projects: ["binutils-gdb@binutils-2_25-branch-nux"])

		stage("Build") {
			onSlurmResource(partition: "jenkins", "cpus-per-task": "8") {
				sish "bash binutils-gdb/ci/00_build_install_eabi.sh"
				sish "rm -rf build_binutils"
				sish "rm -rf install"
				sish "bash binutils-gdb/ci/00_build_install.sh"
			}
		}
	}

} catch (Exception e) {
	notifyFailure(mattermostChannel: "#dls-software")
	throw e as java.lang.Throwable
} finally {
	// Always clean the workspace
	node {
		cleanWs()
	}
}

// Some Jenkins steps fail a build without raising (e.g. archiveArtifacts)
if (currentBuild.currentResult != "SUCCESS") {
	notifyFailure(mattermostChannel: "#dls-software")
}
